### ISSUE TITLE
Update csv method

### ISSUE THREAD

**Issue by bart1** [barthoekstra/birdcloud#1]
Currently I write `csv`s by directly using the pointcloud. That makes it possible to use compression (`compression='gzip'`). This reduces file size about 3 fold. An other 1/3 reduction can be achieved by reducing the significant digits: `float_format='%.8f'` . Maybe there is a way to have the `to_csv` method pass on arguments to the pandas `to_csv`, similar to `...` in R? This would ensure other arguments for writing are always the same (`NaN`) usw.

```
b.to_csv("~/aa1.csv")
b.pointcloud.to_csv("~/aa.csv")
b.pointcloud.to_csv("~/aa.csv.gz", compression='gzip')
b.pointcloud.to_csv("~/aa1.csv.gz", compression='gzip', float_format='%.8f')
```

**Comment by barthoekstra** [comment]
Oh yeah, forgot about that. Now added in db313954f9d9ece5e570f86681bea5bb19f9a50f.
